services:
  - type: web
    name: floormap-web
    runtime: ruby
    runtimeVersion: "3.3.0"
    buildCommand: rm -rf node_modules/.esbuild node_modules/.vite .vite && bundle install && npm ci && npm run build
    startCommand: bash bin/render-start
    envVars:
      - key: REDIS_URL
        fromService:
          name: floormap-redis
          property: connectionString
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: "true"
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"

  - type: redis
    name: floormap-redis
    ipAllowList: []
    plan: starter
